#set($symbol_pound='#')
#set($symbol_dollar='$')
#set($symbol_escape='\' )
server:
  port: 80

spring:
  application:
    name: ${rootArtifactId}

lks:
  $symbol_pound 可选mysql,shardingjdbc,seata,redis,es,mongodb,elasticjob,rocketmq
  enables:

app:
  id: ${spring.application.name}
apollo:
  bootstrap:
    $symbol_pound Apollo开关
    enabled: true
    eagerLoad:
      enabled: true
    namespaces: application


$symbol_pound prometheus
management:
  security:
    enabled: false
  metrics:
    export:
      prometheus:
        enabled: true
      jmx:
        enabled: true
    tags:
      application: ${spring.application.name}
  endpoints:
    web:
      exposure:
        include: '*'
      base-path: /metrics